// <auto-generated />
using System;
using ClickManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickManagerApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FotografoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoEnsaio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FotografoId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marcela@cliente.local",
                            FotografoId = 1,
                            Nome = "MARCELA",
                            Status = "Pausado",
                            TipoEnsaio = "Casamento"
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "virtor@cliente.local",
                            FotografoId = 1,
                            Nome = "Virtor",
                            Status = "Ativo",
                            TipoEnsaio = "Casamento"
                        });
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnsaioId")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EnsaioId")
                        .IsUnique();

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Contratos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnsaioId = 1,
                            Numero = "CTR16778",
                            Status = "Assinado"
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnsaioId = 2,
                            Numero = "CTR13245673",
                            Status = "Assinado"
                        });
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Disponibilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<byte>("DiaSemana")
                        .HasColumnType("tinyint");

                    b.Property<int>("FotografoId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("FotografoId");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Ensaio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("FotografoId")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalImagens")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataHora");

                    b.HasIndex("FotografoId");

                    b.ToTable("Ensaios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtualizadoEm = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClienteId = 1,
                            CriadoEm = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataHora = new DateTime(2026, 3, 25, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FotografoId = 1,
                            Local = "Sorocaba",
                            Status = "Agendado",
                            Titulo = "Festa 15 Anos Marcela",
                            TotalImagens = 0,
                            Valor = 700m
                        },
                        new
                        {
                            Id = 2,
                            AtualizadoEm = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClienteId = 2,
                            CriadoEm = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataHora = new DateTime(2026, 3, 24, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FotografoId = 1,
                            Local = "Igreja",
                            Status = "Agendado",
                            Titulo = "casamento",
                            TotalImagens = 0,
                            Valor = 200m
                        });
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Fotografo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PlanoAtivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Fotografos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtualizadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "matheus@studio.com",
                            Nome = "Matheus",
                            PlanoAtivo = "pro",
                            SenhaHash = "$2a$11$demo_hash_substituir_por_bcrypt"
                        });
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.ImagemGaleria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnsaioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EnsaioId");

                    b.ToTable("ImagensGaleria");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.ImagemPortfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("FotografoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FotografoId");

                    b.ToTable("ImagensPortfolio");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EmailEnviado")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Plano")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnsaioId")
                        .HasColumnType("int");

                    b.Property<string>("Metodo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnsaioId");

                    b.ToTable("Pagamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPagamento = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnsaioId = 1,
                            Metodo = "Pix",
                            Status = "Pago",
                            Tipo = "Total",
                            Valor = 700m
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataPagamento = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnsaioId = 2,
                            Metodo = "Pix",
                            Status = "Pago",
                            Tipo = "Total",
                            Valor = 200m
                        });
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Cliente", b =>
                {
                    b.HasOne("ClickManagerApi.Models.Entities.Fotografo", "Fotografo")
                        .WithMany("Clientes")
                        .HasForeignKey("FotografoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fotografo");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Contrato", b =>
                {
                    b.HasOne("ClickManagerApi.Models.Entities.Ensaio", "Ensaio")
                        .WithOne("Contrato")
                        .HasForeignKey("ClickManagerApi.Models.Entities.Contrato", "EnsaioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ensaio");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Disponibilidade", b =>
                {
                    b.HasOne("ClickManagerApi.Models.Entities.Fotografo", "Fotografo")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("FotografoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fotografo");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Ensaio", b =>
                {
                    b.HasOne("ClickManagerApi.Models.Entities.Cliente", "Cliente")
                        .WithMany("Ensaios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ClickManagerApi.Models.Entities.Fotografo", "Fotografo")
                        .WithMany("Ensaios")
                        .HasForeignKey("FotografoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Fotografo");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.ImagemGaleria", b =>
                {
                    b.HasOne("ClickManagerApi.Models.Entities.Ensaio", "Ensaio")
                        .WithMany("ImagensGaleria")
                        .HasForeignKey("EnsaioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ensaio");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.ImagemPortfolio", b =>
                {
                    b.HasOne("ClickManagerApi.Models.Entities.Fotografo", "Fotografo")
                        .WithMany("Portfolio")
                        .HasForeignKey("FotografoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fotografo");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Pagamento", b =>
                {
                    b.HasOne("ClickManagerApi.Models.Entities.Ensaio", "Ensaio")
                        .WithMany("Pagamentos")
                        .HasForeignKey("EnsaioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ensaio");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Cliente", b =>
                {
                    b.Navigation("Ensaios");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Ensaio", b =>
                {
                    b.Navigation("Contrato");

                    b.Navigation("ImagensGaleria");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("ClickManagerApi.Models.Entities.Fotografo", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Disponibilidades");

                    b.Navigation("Ensaios");

                    b.Navigation("Portfolio");
                });
#pragma warning restore 612, 618
        }
    }
}
